### ISSUE TITLE
Could you also include github universe stickers in the next batch?

### ISSUE THREAD

**Issue by kevinlaiGH** [wesbos/Stickers#2]
<img width="683" alt="screen shot 2017-10-21 at 1 02 52 pm" src="https://user-images.githubusercontent.com/23046844/31847034-43c23a74-b660-11e7-9fcb-f1880b313f7c.png">
<img width="683" alt="screen shot 2017-10-21 at 1 05 04 pm" src="https://user-images.githubusercontent.com/23046844/31847044-7bc59ccc-b660-11e7-9f59-868bfa9cd134.png">

**Comment by sreetamdas** [comment]
if you're looking for Hacktoberfest stickers, you get them for just participation in Hacktoberfest as well 😄
